Chapter 0 and 1 translated to Russian.
huggingface/audio-transformers-course pull request #117
Opened 2023-08-02 10:29 UTC by blademoon

Good afternoon. Chapter 0 and 1 are fully translated. Also added a file on unambiguous translation of some terms for uniformity of translation by different translators.

2023-08-02 13:30 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/learn/audio-course/pr_117). All of your documentation changes will be reflected on that endpoint.

2023-08-02 15:52 UTC, MKhalusova requested changes
Thanks for working on translating the course! Overall, it looks good to me. However, there are still a few changes needed to make sure the translated chapters can be built correctly. Two more files need to be updated in order to build the course in a new language. `.github/workflows/build_documentation.yml` and `.github/workflows/build_pr_documentation.yml`.
Please add `ru` to the list of languages similar to how it's done [here](https://github.com/huggingface/audio-transformers-course/blob/360ba6cffda44d249029f790f03a93b08ec74cb8/.github/workflows/build_documentation.yml#L17).

2023-08-03 06:46 UTC, blademoon commented
@MKhalusova Good afternoon. I'm a bit lacking in experience, but as far as I'm concerned - done. Is everything correct now?

2023-08-03 14:15 UTC, MKhalusova approved these changes
Thank you for addressing the feedback @blademoon! The translated chapters now build correctly and we can merge them in.

2023-08-03 14:15 UTC, merged