Chapter 5 translated to Russian
huggingface/audio-transformers-course pull request #123
Opened 2023-08-14 13:05 UTC by Lightmourne

The translation of chapter 5 has been completed.

Hello, @MKhalusova! I think I found a typo in the evaluation.mdx (line 203) I think the word "target" should be changed to "prediction".
Please let me know if I am wrong.

2023-08-14 13:12 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/learn/audio-course/pr_123). All of your documentation changes will be reflected on that endpoint.

2023-08-18 14:41 UTC, sanchit-gandhi reviewed
Thank you for your contribution @Lightmourne! Let's wait for @MKhalusova to take a look here before merging :)

2023-08-18 14:41 UTC, sanchit-gandhi commented on chapters/en/chapter5/evaluation.mdx
> +transcription and then compute the normalised WER between the reference and prediction:
Good catch!

2023-08-29 13:32 UTC, MKhalusova requested changes
Thank you for your contribution! The translation looks good to me, but there are some checks failing. Please run `make style` to fix formatting issues.

2023-08-29 19:57 UTC, Lightmourne commented
Thank you @MKhalusova !
File formatting was checked :white_check_mark:

2023-08-30 18:07 UTC, merged